### ISSUE TITLE
Unable to select local image if path includes capital letters

### ISSUE THREAD

**Issue by afishydeath** [phthallo/pyflagoras#4]
in `src/pyflagoras/flag_info.py`, in the function `flag_attr` the `flag_alias` is converted to lowercase *before* running `if os.path.exists(flag_alias):`, at least in my case, this results in me being unable to open files in my `~/Downloads` folder, as the folder includes a capital letter.

**Comment by phthallo** [comment]
today i learned about differing case sensitivity on different OSes :pensive: 

thank you for the bug report!
